-- Restocking is additive and always logged as a purchase (log_stock_expense
-- fires whenever stock.quantity rises). There was no way to fix a typo
-- without either leaving it wrong or "restocking" the correction, which
-- would both misrepresent the quantity change and log a second, equally
-- fake expense.
--
-- Adds a superadmin-only correction path that sets a stock item's
-- quantity/price directly, skips the purchase side-effect via the same
-- transaction-local-flag pattern enforce_cancel_via_rpc already uses
-- (app.pin_verified), and records what changed in a small audit table
-- instead — modeled on order_override_log. Also adds a superadmin-only way
-- to delete a bad expenses row a mistaken restock already created, logged
-- the same way.

create table if not exists public.admin_correction_log (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('stock_correction', 'expense_deleted')),
  superadmin_id uuid references public.profiles(id),
  target_name text,
  old_quantity numeric,
  new_quantity numeric,
  old_price_per_unit integer,
  new_price_per_unit integer,
  note text,
  created_at timestamptz not null default now()
);

alter table public.admin_correction_log enable row level security;

drop policy if exists "Superadmin can read admin_correction_log" on public.admin_correction_log;
create policy "Superadmin can read admin_correction_log" on public.admin_correction_log
  for select to public using ((EXISTS ( SELECT 1 FROM profiles
    WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'superadmin'::text)))));

-- No INSERT/UPDATE/DELETE policy — written only by the two SECURITY DEFINER
-- RPCs below, same as order_override_log.

create or replace function public.log_stock_expense()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if coalesce(current_setting('app.stock_correction', true), '') = 'true' then
    return new;
  end if;

  if (tg_op = 'UPDATE' and new.quantity > old.quantity) then
    insert into public.expenses (name, quantity, price_per_unit, expense_date)
    values (new.name, (new.quantity - old.quantity), new.price_per_unit, coalesce(new.last_purchase_date, now()));
  elsif (tg_op = 'INSERT') then
    insert into public.expenses (name, quantity, price_per_unit, expense_date)
    values (new.name, new.quantity, new.price_per_unit, coalesce(new.last_purchase_date, now()));
  end if;
  return new;
end;
$function$;

create or replace function public.correct_stock(
  p_stock_id bigint,
  p_quantity numeric,
  p_price_per_unit integer,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_quantity numeric;
  v_old_price integer;
  v_name text;
begin
  if not exists (select 1 from profiles where id = auth.uid() and role = 'superadmin') then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  select quantity, price_per_unit, name into v_old_quantity, v_old_price, v_name
  from stock where id = p_stock_id;

  perform set_config('app.stock_correction', 'true', true);

  update stock
  set quantity = p_quantity, price_per_unit = p_price_per_unit, updated_at = now()
  where id = p_stock_id;

  insert into admin_correction_log
    (action, superadmin_id, target_name, old_quantity, new_quantity, old_price_per_unit, new_price_per_unit, note)
  values
    ('stock_correction', auth.uid(), v_name, v_old_quantity, p_quantity, v_old_price, p_price_per_unit, p_note);
end;
$$;

revoke all on function public.correct_stock(bigint, numeric, integer, text) from public, anon;
grant execute on function public.correct_stock(bigint, numeric, integer, text) to authenticated;

create or replace function public.delete_expense_entry(p_expense_id bigint, p_note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_quantity numeric;
  v_price integer;
begin
  if not exists (select 1 from profiles where id = auth.uid() and role = 'superadmin') then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  select name, quantity, price_per_unit into v_name, v_quantity, v_price
  from expenses where id = p_expense_id;

  delete from expenses where id = p_expense_id;

  insert into admin_correction_log
    (action, superadmin_id, target_name, old_quantity, old_price_per_unit, note)
  values
    ('expense_deleted', auth.uid(), v_name, v_quantity, v_price, p_note);
end;
$$;

revoke all on function public.delete_expense_entry(bigint, text) from public, anon;
grant execute on function public.delete_expense_entry(bigint, text) to authenticated;
