-- Baseline schema for the Papper project.
--
-- Reconstructed from the live catalog on 2026-08-01, not produced by pg_dump:
-- the Supabase CLI's database commands fail on this project with
-- LegacyDbConfigLoginRoleStatusError (it cannot provision its cli_login_postgres
-- role), and the local pg_dump is version 14 against a Postgres 17 server.
--
-- Scope: the `public` schema only. Auth settings, Storage configuration, and
-- everything outside `public` are NOT captured here and must be reproduced by
-- hand. Row data lives separately in data.sql at the repo root.
--
-- Deliberately excluded, because later migrations create them and would then
-- collide (CREATE POLICY has no IF NOT EXISTS):
--   * cancel_order_with_pin, cancel_order_with_pin_v2, delete_order_with_pin,
--     pin_attempts_exhausted, prevent_direct_cancel,
--     prevent_locked_order_item_change
--   * triggers enforce_cancel_via_rpc, enforce_items_locked_after_payment
--   * index order_override_log_failed_attempts_idx
--   * the `expenses` policies
--
-- If this file is ever regenerated, keep its timestamp ahead of every other
-- migration.

create extension if not exists pgcrypto  with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid not null,
  role text default 'cashier'::text not null,
  name text,
  pin_hash text
);

create table if not exists public.menus (
  id bigint generated always as identity,
  name text not null,
  price integer not null,
  category text not null,
  available boolean default true not null,
  created_at timestamp with time zone default now(),
  cogs_mode text default 'ingredients'::text not null,
  manual_cogs numeric
);

create table if not exists public.stock (
  id bigint generated always as identity,
  name text not null,
  quantity numeric default 0 not null,
  unit text not null,
  price_per_unit integer default 0 not null,
  updated_at timestamp with time zone default now(),
  last_purchase_date timestamp with time zone default now()
);

create table if not exists public.menu_ingredients (
  id bigint generated always as identity,
  menu_id bigint not null,
  stock_id bigint not null,
  quantity numeric not null
);

create table if not exists public.orders (
  id bigint generated always as identity,
  customer_name text not null,
  seat text not null,
  discount integer default 0 not null,
  status text default 'unpaid'::text not null,
  created_at timestamp with time zone default now(),
  method_of_payment text,
  is_dine_in boolean,
  payment_amount integer
);

create table if not exists public.order_items (
  id bigint generated always as identity,
  order_id bigint not null,
  menu_id bigint not null,
  name text not null,
  price integer not null,
  quantity integer not null,
  is_sent boolean default false,
  is_cancelled boolean default false,
  print_batch integer default 1,
  notes text,
  is_stock_deducted boolean
);

create table if not exists public.expenses (
  id bigint generated by default as identity,
  name text not null,
  quantity numeric not null,
  price_per_unit integer not null,
  total_cost numeric generated always as ((quantity * (price_per_unit)::numeric)) stored,
  expense_date timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.order_override_log (
  id bigint generated always as identity,
  order_id bigint,
  cashier_id uuid,
  action text not null,
  success boolean not null,
  created_at timestamp with time zone default now(),
  admin_id uuid
);

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------

alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public.menus add constraint menus_pkey PRIMARY KEY (id);
alter table public.menus add constraint menus_price_check CHECK ((price > 0));
alter table public.menus add constraint menus_cogs_mode_check CHECK ((cogs_mode = ANY (ARRAY['ingredients'::text, 'manual'::text])));
alter table public.menus add constraint menus_manual_cogs_check CHECK (((manual_cogs IS NULL) OR (manual_cogs >= (0)::numeric)));

alter table public.stock add constraint stock_pkey PRIMARY KEY (id);

alter table public.menu_ingredients add constraint menu_ingredients_pkey PRIMARY KEY (id);
alter table public.menu_ingredients add constraint menu_ingredients_quantity_check CHECK ((quantity > (0)::numeric));
alter table public.menu_ingredients add constraint menu_ingredients_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
alter table public.menu_ingredients add constraint menu_ingredients_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES stock(id) ON DELETE CASCADE;

alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_discount_check CHECK (((discount >= 0) AND (discount <= 100)));
alter table public.orders add constraint orders_method_of_payment_check CHECK ((method_of_payment = ANY (ARRAY['QRIS'::text, 'Bank Transfer'::text, 'Cash'::text])));

alter table public.order_items add constraint order_items_pkey PRIMARY KEY (id);
alter table public.order_items add constraint order_items_price_check CHECK ((price > 0));
alter table public.order_items add constraint order_items_quantity_check CHECK ((quantity > 0));
alter table public.order_items add constraint order_items_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id);
alter table public.order_items add constraint order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;

alter table public.expenses add constraint expenses_pkey PRIMARY KEY (id);
alter table public.expenses add constraint expenses_quantity_check CHECK ((quantity > (0)::numeric));
alter table public.expenses add constraint expenses_price_per_unit_check CHECK ((price_per_unit > 0));

alter table public.order_override_log add constraint order_override_log_pkey PRIMARY KEY (id);
alter table public.order_override_log add constraint order_override_log_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
alter table public.order_override_log add constraint order_override_log_cashier_id_fkey FOREIGN KEY (cashier_id) REFERENCES profiles(id);
alter table public.order_override_log add constraint order_override_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES profiles(id);

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, role)
  values (new.id, 'cashier');

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.check_stock_for_order(p_items jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_item record;
  v_ingredient record;
  v_current_quantity numeric;
  v_shortages jsonb := '[]'::jsonb;
begin
  for v_item in
    select (item->>'menu_id')::int as menu_id, (item->>'quantity')::int as quantity
    from jsonb_array_elements(p_items) as item
  loop
    for v_ingredient in
      select mi.stock_id, s.name as stock_name, mi.quantity * v_item.quantity as total_needed
      from menu_ingredients mi
      join stock s on s.id = mi.stock_id
      where mi.menu_id = v_item.menu_id
    loop
      select quantity into v_current_quantity
      from stock
      where id = v_ingredient.stock_id;

      if v_current_quantity < v_ingredient.total_needed then
        v_shortages := v_shortages || jsonb_build_object(
          'stock_id', v_ingredient.stock_id,
          'stock_name', v_ingredient.stock_name,
          'needed', v_ingredient.total_needed,
          'available', v_current_quantity
        );
      end if;
    end loop;
  end loop;

  return jsonb_build_object('shortages', v_shortages);
end;
$function$;

CREATE OR REPLACE FUNCTION public.deduct_stock_for_order(p_order_id integer, p_force boolean DEFAULT false)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_item record;
  v_ingredient record;
  v_current_quantity numeric;
begin
  for v_item in
    select oi.menu_id, oi.quantity
    from order_items oi
    where oi.order_id = p_order_id
      and oi.is_stock_deducted = false
  loop
    for v_ingredient in
      select mi.stock_id, mi.quantity * v_item.quantity as total_needed
      from menu_ingredients mi
      where mi.menu_id = v_item.menu_id
    loop
      select quantity into v_current_quantity
      from stock
      where id = v_ingredient.stock_id
      for update;

      -- Only block if NOT forcing
      if not p_force and v_current_quantity < v_ingredient.total_needed then
        raise exception 'Insufficient stock for stock_id %', v_ingredient.stock_id
          using errcode = 'P0001';
      end if;

      update stock
      set quantity = quantity - v_ingredient.total_needed,
          updated_at = now()
      where id = v_ingredient.stock_id;
    end loop;
  end loop;

  update order_items
  set is_stock_deducted = true
  where order_id = p_order_id
    and is_stock_deducted = false;
end;
$function$;

CREATE OR REPLACE FUNCTION public.log_stock_expense()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    -- Handle UPDATE: Only log if the stock quantity actually went up
    IF (TG_OP = 'UPDATE' AND NEW.quantity > OLD.quantity) THEN
        INSERT INTO public.expenses (name, quantity, price_per_unit, expense_date)
        VALUES (
            NEW.name,
            (NEW.quantity - OLD.quantity), -- The newly added amount
            NEW.price_per_unit,
            COALESCE(NEW.last_purchase_date, now())
        );
    -- Handle INSERT: Brand new stock item
    ELSIF (TG_OP = 'INSERT') THEN
        INSERT INTO public.expenses (name, quantity, price_per_unit, expense_date)
        VALUES (
            NEW.name,
            NEW.quantity,
            NEW.price_per_unit,
            COALESCE(NEW.last_purchase_date, now())
        );
    END IF;
    RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

drop trigger if exists after_stock_change on public.stock;
CREATE TRIGGER after_stock_change AFTER INSERT OR UPDATE ON public.stock
  FOR EACH ROW EXECUTE FUNCTION log_stock_expense();

-- Lives on auth.users, so it is outside the `public` scope of this file but is
-- required for profile creation to work at all.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.profiles           enable row level security;
alter table public.menus              enable row level security;
alter table public.stock              enable row level security;
alter table public.menu_ingredients   enable row level security;
alter table public.orders             enable row level security;
alter table public.order_items        enable row level security;
alter table public.expenses           enable row level security;
alter table public.order_override_log enable row level security;

create policy "Users can read own profile" on public.profiles
  for select to public using ((auth.uid() = id));

create policy "Anyone can read menus" on public.menus
  for select to public using (true);
create policy "Admin can manage menus" on public.menus
  for all to public using ((EXISTS ( SELECT 1 FROM profiles
    WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

create policy "Admin can manage stock" on public.stock
  for all to public using ((EXISTS ( SELECT 1 FROM profiles
    WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

create policy "Anyone can read menu_ingredients" on public.menu_ingredients
  for select to public using (true);
create policy "Admin can manage menu_ingredients" on public.menu_ingredients
  for all to public using ((EXISTS ( SELECT 1 FROM profiles
    WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

-- Note the duplicated pairs on orders: two overlapping permissive SELECT
-- policies and two overlapping UPDATE policies. Permissive policies OR together,
-- so the `using (true)` pair is what actually applies. Preserved as-is because
-- this is a faithful baseline, but it is worth collapsing.
create policy "Authenticated can read orders" on public.orders
  for select to public using ((auth.role() = 'authenticated'::text));
create policy "authenticated can read orders" on public.orders
  for select to authenticated using (true);
create policy "Authenticated can insert orders" on public.orders
  for insert to public with check ((auth.role() = 'authenticated'::text));
create policy "Authenticated can update orders" on public.orders
  for update to public using ((auth.role() = 'authenticated'::text));
create policy "authenticated can update orders" on public.orders
  for update to authenticated using (true);

create policy "Authenticated can read order_items" on public.order_items
  for select to public using ((auth.role() = 'authenticated'::text));
create policy "Authenticated can insert order_items" on public.order_items
  for insert to public with check ((auth.role() = 'authenticated'::text));
create policy "Authenticated can update order_items" on public.order_items
  for update to public using ((auth.role() = 'authenticated'::text));
create policy "Authenticated can delete order_items" on public.order_items
  for delete to public using ((auth.role() = 'authenticated'::text));

create policy "admins can read override log" on public.order_override_log
  for select to authenticated using ((EXISTS ( SELECT 1 FROM profiles
    WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant all on public.menus, public.stock, public.menu_ingredients,
             public.order_items, public.order_override_log
  to anon, authenticated, service_role;

-- authenticated has no DELETE: hard deletes would sidestep the cancellation
-- trigger added in 20260801120000.
grant all on public.orders to anon, service_role;
grant select, insert, update, references, trigger, truncate
  on public.orders to authenticated;

-- anon has nothing on expenses; see 20260801140000.
grant all on public.expenses to authenticated, service_role;

-- profiles is column-restricted so pin_hash never reaches a client;
-- see 20260801120000.
grant all on public.profiles to service_role;
grant insert, update, delete, references, trigger, truncate
  on public.profiles to anon, authenticated;
grant select (id, role, name) on public.profiles to anon, authenticated;
